version: '3.8'

services:
    web:
        build: #../app 
          context: ../app
          dockerfile: Dockerfile.prod
        command: gunicorn app_config.wsgi:application --bind 0.0.0.0:8000  
        volumes:
            - ../app/:/usr/src/app/
        # ports:
        #     - 8080:8000
        expose:
          - 8000
        env_file:
          - ../app/.env.prod

    db:
        image: postgres:13.0-alpine
        volumes:
          - postgres_data:/var/lib/postgresql/data/
        env_file:
          - ../app/.env.prod.db
        environment:
          - POSTGRES_USER=tranlequybao
          - POSTGRES_PASSWORD=complexpassword
          - POSTGRES_DB=postgres
    nginx:
        build: ../nginx
        ports:
          - 1337:80
        depends_on:
          - web

volumes:
    postgres_data:

