version: '3.8'

services:
    web:
        build: ../app 
        command: python3.8 ../app/manage.py runserver 0.0.0.0:8000  
        volumes:
            - ../app/:/usr/src/app/
        ports:
            - 8080:8000
        env_file:
          - ../app/.env.dev

    db:
        image: postgres:13.0-alpine
        volumes:
          - postgres_data:/var/lib/postgresql/data/
        environment:
          - POSTGRES_USER=tranlequybao
          - POSTGRES_PASSWORD=complexpassword
          - POSTGRES_DB=postgres

volumes:
    postgres_data:

