# Generated by Django 3.2.6 on 2024-07-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MailTemp",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("account_id", models.PositiveIntegerField()),
                ("hash", models.CharField(max_length=255)),
                ("expire_time", models.DateTimeField()),
            ],
            options={
                "db_table": "mail_temps",
            },
        ),
    ]
